name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release and publish to PyPI
        uses: seriaati/create-release@v1.0.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          tool: uv
